# Uncomment this line to define a global platform for your project

# Uncomment this line if you're using Swift


target 'newsReader' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'newsReaderTests' do

end

target 'newsReaderUITests' do

end

 platform :ios, '8.0'
 use_frameworks!